library(pls)
library(glmnet)
library(xtable)
library(testthat)
library(Matrix)
library(devtools)
library(knitr)

sink("../../session-info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
devtools::session_info()
sink()